/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-04 02:54:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class users_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("<!-- Link cho Font Awesome 5.x (hỗ trợ cả phiên bản free và pro) -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Link cho Font Awesome 6.x (bản beta) -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".main-content {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn i {\r\n");
      out.write("	font-size: 0.8em; /* Điều chỉnh tỷ lệ thu nhỏ, ví dụ 0.8em */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-text {\r\n");
      out.write("	color: #343a40; /* Màu xám đậm */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layouts/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"main-content\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layouts/navigation.jsp", out, false);
      out.write("\r\n");
      out.write("		<div class=\"container-fluid d-flex flex-column\"\r\n");
      out.write("			style=\"padding-left: 0px; padding-right: 0px;\">\r\n");
      out.write("			<div class=\"container-fluid\"\r\n");
      out.write("				style=\"margin-left: 0px; margin-right: 0px;\">\r\n");
      out.write("				<div class=\"row g-3 mt-3\">\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<h2 class=\"h3\">User management</h2>\r\n");
      out.write("						<p>Manage users, roles, permissions, and profile.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-auto d-none d-sm-block\">\r\n");
      out.write("						<img class=\"page-icon\" src=\"resources/images/page.svg\"\r\n");
      out.write("							width=\"120px\" alt=\"Page Icon\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form id=\"frm-admin\" name=\"adminForm\" action=\"\" method=\"POST\">\r\n");
      out.write("				<input type=\"hidden\" id=\"task\" name=\"task\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.task}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" id=\"sortby\" name=\"sortby\"\r\n");
      out.write("					value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sortby != null ? param.sortby : 'updated_at'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input\r\n");
      out.write("					type=\"hidden\" id=\"orderby\" name=\"orderby\"\r\n");
      out.write("					value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.orderby != null ? param.orderby : 'desc'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input\r\n");
      out.write("					type=\"hidden\" id=\"boxchecked\" name=\"boxchecked\" value=\"0\" />\r\n");
      out.write("\r\n");
      out.write("				<div class=\"card mx-3\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"d-flex gap-3\">\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input class=\"form-control search-input\" name=\"search_text\"\r\n");
      out.write("									id=\"search_text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.search_text}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("									placeholder=\"Search ...\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-secondary btn-search\">\r\n");
      out.write("									<i class=\"fa fa-search\"></i>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"btn btn-primary text-nowrap btn-add\"\r\n");
      out.write("								href=\"saga/users/edit\"><i class=\"fa fa-plus me-2\"></i>Add</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"table-actionbar bg-primary bg-opacity-10 p-2 ps-3 d-none\">\r\n");
      out.write("								<div class=\"d-flex justify-content-between gap-3\">\r\n");
      out.write("									<div class=\"selected-count align-self-center\"></div>\r\n");
      out.write("									<div class=\"d-flex gap-1\">\r\n");
      out.write("										<a class=\"btn btn-rounded btn-publish\"><i\r\n");
      out.write("											class=\"fa fa-eye\"></i></a> <a\r\n");
      out.write("											class=\"btn btn-rounded btn-unpublish\"><i\r\n");
      out.write("											class=\"fa fa-eye-slash\"></i></a> <a\r\n");
      out.write("											class=\"btn btn-rounded btn-delete\"><i\r\n");
      out.write("											class=\"fa fa-trash-alt\"></i></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"table-responsive\">\r\n");
      out.write("								<table class=\"table table-centered\">\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th width=\"30px\"><input class=\"form-check-input\"\r\n");
      out.write("											type=\"checkbox\" id=\"toggle\" name=\"toggle\"\r\n");
      out.write("											onclick=\"checkAll()\" /></th>\r\n");
      out.write("										<th width=\"30px\" class=\"text-end\">#</th>\r\n");
      out.write("										<th>Name</th>\r\n");
      out.write("										<th width=\"60px\">Roles</th>\r\n");
      out.write("										<th width=\"60px\" class=\"text-end\">Status</th>\r\n");
      out.write("										<th width=\"160px\" class=\"text-end\">Updated</th>\r\n");
      out.write("										<th width=\"60px\">Actions</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<c:forEach var=\"user\" items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${users}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" varStatus=\"status\">\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td><input type=\"checkbox\" class=\"form-check-input\"\r\n");
      out.write("												id=\"cb");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"cid[]\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.uuid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("												onclick=\"isChecked(this.checked)\"></td>\r\n");
      out.write("											<td class=\"text-end\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(users.page - 1) * users.pageSize + status.index + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("											<td><a class=\"d-flex flex-nowrap align-items-center\"\r\n");
      out.write("												href=\"saga/users/edit/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.uuid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("													<div>\r\n");
      out.write("														<img alt=\"User Avatar\"\r\n");
      out.write("															src=\"resources/images/TrinhThangBinh.jpg\"\r\n");
      out.write("															class=\"rounded-circle bg-white border border-3 border-white\"\r\n");
      out.write("															width=\"30px\">\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"ms-3\">\r\n");
      out.write("														<div class=\"fw-semibold custom-text\" style=\"text-decoration: none;\">Vo Anh Phung</div>\r\n");
      out.write("														<div class=\"small custom-text\">pppp@gmail.com</div>\r\n");
      out.write("													</div>\r\n");
      out.write("											</a></td>\r\n");
      out.write("											<td><span\r\n");
      out.write("												class=\"small text-uppercase text-success bg-success bg-opacity-10 rounded px-2 py-1\">admin</span>\r\n");
      out.write("											</td>\r\n");
      out.write("											<td class=\"text-end\"><span\r\n");
      out.write("												class=\"small text-uppercase ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.isActive ? 'text-success' : 'text-danger'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" bg-opacity-10 rounded px-2 py-1\">\r\n");
      out.write("													");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.isActive ? 'Active' : 'Inactive'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </span></td>\r\n");
      out.write("											<td class=\"text-end\">22:00 14/11/2024</td>\r\n");
      out.write("											<td class=\"text-end\">\r\n");
      out.write("												<div class=\"d-flex gap-1\">\r\n");
      out.write("													<a class=\"btn btn-rounded\" href=\"#\"><i\r\n");
      out.write("														class=\"fa fa-pencil\"></i></a> <a class=\"btn btn-rounded\"><i\r\n");
      out.write("														class=\"fa ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.isActive ? 'fa-eye-slash' : 'fa-eye'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></i></a>\r\n");
      out.write("													<a class=\"btn btn-rounded\"><i class=\"fa fa-arrow-up\"></i></a>\r\n");
      out.write("													<a class=\"btn btn-rounded\"><i class=\"fa fa-arrow-down\"></i></a>\r\n");
      out.write("													<a class=\"btn btn-rounded\"><i class=\"fa fa-trash-alt\"></i></a>\r\n");
      out.write("												</div>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</c:forEach>\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${users.links}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
